import { For, state } from '@askrjs/askr';
import { Link } from '@askrjs/askr/router';
import { CheckCircleIcon } from '@askrjs/lucide';
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  EmptyState,
  Grid,
  PageHeader,
  Stack,
} from '@askrjs/themes/components';
import { findRunbook, runbooks } from './data.js';
import { SiteLayout } from './components/site-layout.js';

export function HomePage() {
  return (
    <SiteLayout>
      <PageHeader title="Public operations runbooks" description="Static, deterministic recovery guidance generated by Askr." />
      <Grid columns={{ base: 1, md: 2 }} gap="md">
        <For each={runbooks} by={(runbook) => runbook.slug}>
          {(runbook) => (
            <Card>
              <CardHeader><CardTitle>{runbook.title}</CardTitle><CardDescription>{runbook.summary}</CardDescription></CardHeader>
              <CardContent><Button asChild variant="outline"><Link href={`/runbooks/${runbook.slug}`}>Open runbook</Link></Button></CardContent>
            </Card>
          )}
        </For>
      </Grid>
    </SiteLayout>
  );
}

export function RunbookPage({ slug }: { slug: string }) {
  const runbook = findRunbook(slug);
  const [acknowledged, setAcknowledged] = state(false);
  if (!runbook) {
    return <SiteLayout><EmptyState title="Runbook not found" action={<Button asChild><Link href="/">Return home</Link></Button>} /></SiteLayout>;
  }
  return (
    <SiteLayout>
      <PageHeader title={runbook.title} description={runbook.summary} />
      <Card>
        <CardHeader><CardTitle>Recovery checklist</CardTitle></CardHeader>
        <CardContent>
          <Stack as="ol" gap="3">
            <For each={runbook.steps} by={(step) => step}>
              {(step) => <li>{step}</li>}
            </For>
          </Stack>
        </CardContent>
      </Card>
      <Button
        variant={acknowledged() ? 'outline' : 'primary'}
        aria-pressed={acknowledged() ? 'true' : 'false'}
        onPress={() => setAcknowledged((current) => !current)}
      >
        <CheckCircleIcon aria-hidden="true" />
        {acknowledged() ? 'Runbook acknowledged' : 'Acknowledge this runbook'}
      </Button>
      {acknowledged() ? <Badge role="status">Interactive control hydrated</Badge> : null}
    </SiteLayout>
  );
}
